DEVICE          : cuda              # device used for training and evaluation (cpu, cuda, cuda0, cuda1, ...)
SAVE_DIR        : '/scratch/izar/yju/segformer'         # output folder name used for saving the model, logs and inference results

MODEL:                                    
  NAME          : SegFormer                                           # name of the model you are using
  BACKBONE      : MiT-B2                                                 # model variant
  PRETRAINED    : ''              # backbone model's weight 

DATASET:
  NAME          : SwissOkutama                                          # dataset name to be trained with (camvid, cityscapes, ade20k)
  ROOT          : '/work/vita/datasets/Okutama-Swiss-dataset'                                 # dataset root path
  IGNORE_LABEL  : 255
  TRAIN_SET     : '/work/vita/datasets/Okutama-Swiss-dataset/crossval2/train.lst'
  VAL_SET       : '/work/vita/datasets/Okutama-Swiss-dataset/crossval2/val.lst'
  TEST_SET      : '/work/vita/datasets/Okutama-Swiss-dataset/crossval2/test.lst'
  NUM_CLASSES   : 8

TRAIN:
  IMAGE_SIZE    : [768, 1080]    # training image size in (h, w)
  BATCH_SIZE    : 16               # batch size used to train
  EPOCHS        : 200             # number of epochs to train
  EVAL_INTERVAL : 20              # evaluation interval during training
  AMP           : false           # use AMP in training
  DDP           : false           # use DDP training

LOSS:
  NAME          : CrossEntropy          # loss function name (ohemce, ce, dice)
  CLS_WEIGHTS   : true            # use class weights in loss calculation

OPTIMIZER:
  NAME          : adamw           # optimizer name
  LR            : 0.01           # initial learning rate used in optimizer
  WEIGHT_DECAY  : 0.01            # decay rate used in optimizer 

SCHEDULER:
  NAME          : warmuppolylr    # scheduler name
  POWER         : 0.9             # scheduler power
  WARMUP        : 10              # warmup epochs used in scheduler
  WARMUP_RATIO  : 0.1             # warmup ratio
  

EVAL:
  MODEL_PATH    : 'output_08_23/DDRNet_DDRNet-23slim_SwissOkutama.pth'     # trained model file path
  IMAGE_SIZE    : [768, 1080]                           # evaluation image size in (h, w)                       
  MSF: 
    ENABLE      : false                                   # multi-scale and flip evaluation  
    FLIP        : true                                    # use flip in evaluation  
    SCALES      : [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]       # scales used in MSF evaluation                


TEST:
  MODEL_PATH    : 'output_08_23/DDRNet_DDRNet-23slim_SwissOkutama.pth'     # trained model file path
  FILE          : '/work/vita/datasets/Okutama-Swiss-dataset'                    # filename or foldername 
  IMAGE_SIZE    : [768, 1080]                            # inference image size in (h, w)
  OVERLAY       : false                                    # save the overlay result (image_alpha+label_alpha)
